import 'package:flutter/widgets.dart';

class S {
  static const Map<String, Map<String, String>> _t = {
    'uk': {
      'app_title': 'CashChecker',

      'tab_home': 'Головна',
      'tab_history': 'Історія',
      'tab_calendar': 'Календар',
      'tab_add': 'Додати',
      'tab_debts': 'Борги',

      'home_title': 'Головна',
      'total_balance': 'Загальний баланс',
      'total_expense_month': 'Загальні витрати за місяць',
      'your_accounts': 'Ваші рахунки',
      'no_accounts': 'Рахунків поки немає',
      'delete_account': 'Видалити рахунок',
      'delete_confirm': 'Рахунок і всі його операції будуть видалені.',
      'clear_account': 'Очистити рахунок',
      'clear_account_confirm': 'Усі операції рахунку будуть видалені.',
      'account_deleted': 'Рахунок видалено',
      'account_cleared': 'Рахунок очищено',
      'cancel': 'Скасувати',
      'delete': 'Видалити',
      'clear': 'Очистити',

      'add_title': 'Додати',
      'add_transaction': 'Додати операцію',
      'add_account': 'Додати рахунок',
      'name': 'Назва',
      'type': 'Тип',
      'currency': 'Валюта',
      'amount': 'Сума',
      'initial_balance': 'Початковий баланс',
      'save': 'Зберегти',
      'note': 'Нотатка',
      'category': 'Категорія',
      'date': 'Дата',
      'account': 'Рахунок',
      'income': 'Дохід',
      'expense': 'Витрата',
      'account_added': 'Рахунок додано',
      'transaction_added': 'Операцію додано',
      'select_account': 'Оберіть рахунок',
      'select_category': 'Оберіть категорію',
      'transaction_save_failed': 'Не вдалося зберегти операцію',
      'field_required': 'Обовʼязкове поле',
      'invalid_amount': 'Некоректна сума',
      'hide_keyboard': 'Сховати клавіатуру',

      'manage_categories': 'Керування категоріями',
      'new_category': 'Нова категорія',
      'category_added': 'Категорію додано',
      'category_deleted': 'Категорію видалено',
      'delete_category': 'Видалити категорію',
      'delete_category_confirm': 'Категорія буде видалена.',
      'no_categories': 'Немає категорій',

      'history_title': 'Історія',
      'period': 'Період',
      'from': 'Від',
      'to': 'До',
      'apply': 'Застосувати',
      'reset': 'Скинути',
      'all_accounts': 'Усі рахунки',
      'all_types': 'Усі типи',
      'total_operations': 'Загальна сума операцій',
      'no_transactions': 'Операцій немає',
      'delete_operation': 'Видалити операцію',
      'operation_deleted': 'Операцію видалено',

      'calendar_title': 'Календар',
      'month': 'Місяць',
      'month_expenses': 'Витрати за місяць',
      'select_range': 'Вибрати період',
      'range_total': 'Сума за період',
      'by_category': 'По категоріях',

      'debts_title': 'Борги',
      'add_debt': 'Додати борг',
      'person_name': 'Імʼя',
      'direction': 'Напрям',
      'i_lent': 'Я дав',
      'i_borrowed': 'Я взяв',
      'remaining': 'Залишок',
      'record_payment': 'Записати повернення',
      'paid_amount': 'Сума повернення',
      'payment_date': 'Дата повернення',
      'debt_added': 'Борг додано',
      'payment_added': 'Повернення додано',
      'no_debts': 'Боргів немає',

      'planned_expenses': 'Планові витрати',
      'add_planned_expense': 'Додати планову витрату',
      'planned_name': 'Назва збору/плану',
      'planned_amount': 'Планова сума',
      'planned_date': 'Планова дата',
      'planned_added': 'Планову витрату додано',
      'no_planned': 'Немає планових витрат',

      'onboarding_title_1': 'Ласкаво просимо в CashChecker',
      'onboarding_body_1': 'Додавайте рахунки та контролюйте баланс.',
      'onboarding_title_2': 'Облік витрат і доходів',
      'onboarding_body_2': 'Фіксуйте операції по категоріях.',
      'onboarding_title_3': 'Історія, календар і борги',
      'onboarding_body_3': 'Фільтруйте періоди та ведіть повернення боргів.',
      'next': 'Далі',
      'start': 'Почати',
      'skip': 'Пропустити',
    },
    'en': {
      'app_title': 'CashChecker',

      'tab_home': 'Home',
      'tab_history': 'History',
      'tab_calendar': 'Calendar',
      'tab_add': 'Add',
      'tab_debts': 'Debts',
      'home_title': 'Home',
      'total_balance': 'Total balance',
      'total_expense_month': 'Monthly expenses',
      'your_accounts': 'Your accounts',
      'no_accounts': 'No accounts yet',
      'delete_account': 'Delete account',
      'delete_confirm': 'Account and all its transactions will be deleted.',
      'clear_account': 'Clear account',
      'clear_account_confirm': 'All account transactions will be deleted.',
      'account_deleted': 'Account deleted',
      'account_cleared': 'Account cleared',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'clear': 'Clear',

      'add_title': 'Add',
      'add_transaction': 'Add transaction',
      'add_account': 'Add account',
      'name': 'Name',
      'type': 'Type',
      'currency': 'Currency',
      'amount': 'Amount',
      'initial_balance': 'Initial balance',
      'save': 'Save',
      'note': 'Note',
      'category': 'Category',
      'date': 'Date',
      'account': 'Account',
      'income': 'Income',
      'expense': 'Expense',
      'account_added': 'Account added',
      'transaction_added': 'Transaction added',
      'select_account': 'Select an account',
      'select_category': 'Select a category',
      'transaction_save_failed': 'Failed to save transaction',
      'field_required': 'Required field',
      'invalid_amount': 'Invalid amount',
      'hide_keyboard': 'Hide keyboard',

      'manage_categories': 'Manage categories',
      'new_category': 'New category',
      'category_added': 'Category added',
      'category_deleted': 'Category deleted',
      'delete_category': 'Delete category',
      'delete_category_confirm': 'Category will be deleted.',
      'no_categories': 'No categories',

      'history_title': 'History',
      'period': 'Period',
      'from': 'From',
      'to': 'To',
      'apply': 'Apply',
      'reset': 'Reset',
      'all_accounts': 'All accounts',
      'all_types': 'All types',
      'total_operations': 'Total operations amount',
      'no_transactions': 'No transactions',
      'delete_operation': 'Delete operation',
      'operation_deleted': 'Operation deleted',

      'calendar_title': 'Calendar',
      'month': 'Month',
      'month_expenses': 'Month expenses',
      'select_range': 'Select range',
      'range_total': 'Range total',
      'by_category': 'By categories',

      'debts_title': 'Debts',
      'add_debt': 'Add debt',
      'person_name': 'Person name',
      'direction': 'Direction',
      'i_lent': 'I lent',
      'i_borrowed': 'I borrowed',
      'remaining': 'Remaining',
      'record_payment': 'Record payment',
      'paid_amount': 'Paid amount',
      'payment_date': 'Payment date',
      'debt_added': 'Debt added',
      'payment_added': 'Payment added',
      'no_debts': 'No debts',

      'planned_expenses': 'Planned expenses',
      'add_planned_expense': 'Add planned expense',
      'planned_name': 'Collection/plan name',
      'planned_amount': 'Planned amount',
      'planned_date': 'Planned date',
      'planned_added': 'Planned expense added',
      'no_planned': 'No planned expenses',

      'onboarding_title_1': 'Welcome to CashChecker',
      'onboarding_body_1': 'Add accounts and track balances.',
      'onboarding_title_2': 'Track income and expenses',
      'onboarding_body_2': 'Save transactions by categories.',
      'onboarding_title_3': 'History, calendar and debts',
      'onboarding_body_3': 'Filter periods and track debt repayments.',
      'next': 'Next',
      'start': 'Start',
      'skip': 'Skip',
    },
  };

  static String of(Locale locale, String key) {
    final lang = _t[locale.languageCode] ?? _t['en']!;
    return lang[key] ?? _t['en']![key] ?? key;
  }
}